kind = "mobile"
previewPath = "/"
title = "FaithConnect"
version = "1.0.0"
id = "artifacts/faithconnect"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 20924

[services.development]
run = "pnpm --filter @workspace/faithconnect run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/faithconnect", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/faithconnect", "run", "serve" ]

[services.env]
PORT = "20924"
BASE_PATH = "/"
